name: Convert Managed Disk to Azure Image and Publish to Gallery

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:
    #branches:
     # - test

jobs:
  create-and-publish-image:
    runs-on: self-hosted  # Use a GitHub-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID1 }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID1 }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID1 }}

      - name: Create Image from Managed Disk
        run: |
          az image create `
            --resource-group "Test_VM" `
            --name "testimage" `
            --source "/subscriptions/1901eaa9-e98f-49b6-ac39-b1cd55defe19/resourceGroups/Test_VM/providers/Microsoft.Compute/disks/ManagedDisk-2-0-0" `
            --os-type  "Windows" `
            --hyper-v-generation "V2"
      - name: Publish Image to Compute Gallery
        run: |
          az sig image-version create `
            --resource-group "West US " `
            --gallery-name "AzurepackerImages" `
            --gallery-image-definition "win2019dcx64" `
            --gallery-image-version 1.0.0 `
            --managed-image "/subscriptions/1901eaa9-e98f-49b6-ac39-b1cd55defe19/resourceGroups/Test_VM/providers/Microsoft.Compute/images/testimage"

      
