name: Export SIG Image Versions to Managed Disks

on:
  workflow_dispatch:  # Allows manual trigger

env:
  AZURE_SUBSCRIPTION_ID: "your-subscription-id"
  SOURCE_RESOURCE_GROUP: "rg-packer-acg"
  DESTINATION_RESOURCE_GROUP: "Test_VM"
  GALLERY_NAME: "AzurepackerImages"
  IMAGE_DEFINITION: "linux8x64"
  LOCATION: "West US"

permissions:
     id-token: write
     contents: read

jobs:
  export-sig-images:
    runs-on: self-hosted
    steps:

      # Step 1: Login to Azure
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID1 }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID1 }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID1 }}

      # Step 2: Get Image Versions from SIG
      - name: Get Image Versions
        id: get-versions
        run: |
              $IMAGE_VERSIONS = az sig image-version list `
              --resource-group $env:SOURCE_RESOURCE_GROUP `
                --gallery-name $env:GALLERY_NAME `
               --gallery-image-definition $env:IMAGE_DEFINITION `
                  --query "[].{version:name}" `
                 --output tsv | Sort-Object

                   Write-Output "Image Versions Found:"
                Write-Output "$IMAGE_VERSIONS"
  
                   $count = ($IMAGE_VERSIONS -split "`n").Count
                   Write-Output "Total versions: $count"

      # Step 3: Create Managed Disks for Each Image Version
      - name: Create Managed Disks
        run: |
          
          foreach ($IMAGE_VERSION in $IMAGE_VERSIONS -split "`r`n") {
            $DISK_NAME = "ManagedDisk-$IMAGE_VERSION"
            Write-Output "Creating Managed Disk for image version: $IMAGE_VERSION"

            
            az disk create `
              --resource-group $env:DESTINATION_RESOURCE_GROUP `
              --name $DISK_NAME `
              --location $env:LOCATION `
              --gallery-image-reference "/subscriptions/$env:AZURE_SUBSCRIPTION_ID/resourceGroups/$env:SOURCE_RESOURCE_GROUP/providers/Microsoft.Compute/galleries/$env:GALLERY_NAME/images/$env:IMAGE_DEFINITION/versions/$IMAGE_VERSION"
          done

      # Step 4: Move Managed Disks to Another Resource Group
      - name: Move Managed Disks
        run: |
          DISK_IDS=$(az disk list --resource-group $DESTINATION_RESOURCE_GROUP --query "[].id" -o tsv)
          
          if [ -n "$DISK_IDS" ]; then
            echo "Moving Managed Disks to Resource Group: $DESTINATION_RESOURCE_GROUP..."
            az resource move --destination-group $DESTINATION_RESOURCE_GROUP --ids $DISK_IDS
          else
            echo "No disks found to move."
          fi
